const STORAGE_KEYS={points:'user_points',bets:'user_bets',profile:'user_profile',odds:'odds_snapshots'};
const demoMatches=[
{id:'wc2026-001',date:'2026-06-11',time:'20:00',home:'Mexico',away:'South Africa',group:'Group A',venue:'Estadio Azteca',status:'soon',score:'0 - 0'},
{id:'wc2026-002',date:'2026-06-12',time:'18:00',home:'Canada',away:'Japan',group:'Group B',venue:'BMO Field',status:'soon',score:'0 - 0'},
{id:'wc2026-003',date:'2026-06-13',time:'21:00',home:'United States',away:'Germany',group:'Group C',venue:'MetLife Stadium',status:'live',score:'1 - 1'},
{id:'wc2026-004',date:'2026-06-14',time:'17:00',home:'Brazil',away:'Morocco',group:'Group D',venue:'SoFi Stadium',status:'soon',score:'0 - 0'},
{id:'wc2026-005',date:'2026-06-15',time:'19:30',home:'Argentina',away:'Spain',group:'Group E',venue:'AT&T Stadium',status:'soon',score:'0 - 0'},
{id:'wc2026-final',date:'2026-07-19',time:'19:00',home:'TBD Finalist 1',away:'TBD Finalist 2',group:'Final',venue:'MetLife Stadium',status:'future',score:'0 - 0'}];
const teams=[['Mexico','A',84,'S. Giménez'],['South Africa','A',72,'P. Tau'],['Canada','B',79,'A. Davies'],['Japan','B',82,'K. Mitoma'],['United States','C',81,'C. Pulisic'],['Germany','C',88,'J. Musiala'],['Brazil','D',91,'Vinícius Jr.'],['Morocco','D',83,'A. Hakimi'],['Argentina','E',90,'L. Messi'],['Spain','E',89,'Pedri']];
const baseOdds={'wc2026-001':{HOME:1.86,DRAW:3.35,AWAY:4.20},'wc2026-002':{HOME:2.18,DRAW:3.10,AWAY:3.05},'wc2026-003':{HOME:2.45,DRAW:3.40,AWAY:2.62},'wc2026-004':{HOME:1.72,DRAW:3.85,AWAY:5.2},'wc2026-005':{HOME:2.55,DRAW:3.25,AWAY:2.7},'wc2026-final':{HOME:2.05,DRAW:3.25,AWAY:3.45}};
let currentPoints=Number.parseInt(localStorage.getItem(STORAGE_KEYS.points),10)||100;let selectedMatchId=demoMatches[0].id;
const $=id=>document.getElementById(id);const readJson=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};const writeJson=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function label(s){return{HOME:'主胜',DRAW:'平局',AWAY:'客胜'}[s]||s}function updatePoints(n=currentPoints){currentPoints=n;localStorage.setItem(STORAGE_KEYS.points,String(n));$('user-points').innerText=n}
function getCurrentOdds(id){const seed=baseOdds[id]||{HOME:2,DRAW:3.2,AWAY:3.4};const wave=((Date.now()/20000)%1-.5)/8;return{HOME:+(seed.HOME+wave).toFixed(2),DRAW:+(seed.DRAW-wave/2).toFixed(2),AWAY:+(seed.AWAY-wave).toFixed(2),updatedAt:new Date().toISOString()}}
function prediction(match){const o=getCurrentOdds(match.id);const inv={HOME:1/o.HOME,DRAW:1/o.DRAW,AWAY:1/o.AWAY};const sum=inv.HOME+inv.DRAW+inv.AWAY;return{HOME:Math.round(inv.HOME/sum*100),DRAW:Math.round(inv.DRAW/sum*100),AWAY:Math.round(inv.AWAY/sum*100)}}
function renderMatchSelect(){ $('match-select').innerHTML=demoMatches.map(m=>`<option value="${m.id}">${m.date} ${m.home} vs ${m.away}</option>`).join('');$('match-select').value=selectedMatchId}
function renderSelectedMatch(){const m=demoMatches.find(x=>x.id===selectedMatchId);$('selected-match-card').innerHTML=`<div class="team-name">${m.home} vs ${m.away}</div><div class="small text-secondary">${m.group} · ${m.date} ${m.time} · ${m.venue}</div>`;$('hero-match-title').innerText=`${m.home} vs ${m.away}`;$('hero-match-meta').innerText=`${m.group} · ${m.date} ${m.time} · ${m.venue}`;[$('hero-home-score').innerText,$('hero-away-score').innerText]=m.score.split(' - ')}
function oddsButtons(id,cls='odds-button'){const o=getCurrentOdds(id);return['HOME','DRAW','AWAY'].map(s=>`<button class="${cls}" data-selection="${s}" data-match-id="${id}"><span>${label(s)}</span><strong>${o[s].toFixed(2)}</strong></button>`).join('')}
function renderOdds(){$('odds-panel').innerHTML=oddsButtons(selectedMatchId);$('hero-odds').innerHTML=oddsButtons(selectedMatchId,'quick-odd')}
function renderMatches(){const html=demoMatches.map(m=>`<article class="match-card"><div><div class="team-name">${m.home}</div><small>${m.venue}</small></div><div class="score-pill">${m.score}</div><div><div class="team-name">${m.away}</div><small>${m.group} · ${m.date} ${m.time}</small></div><button class="btn btn-sm btn-outline-warning pick-match" data-match-id="${m.id}">${m.status==='live'?'进入直播':'投注'}</button></article>`).join('');$('featured-matches').innerHTML=html;$('schedule-list').innerHTML=html;$('today-count').innerText=demoMatches.filter(m=>m.date<='2026-06-18').length}
function renderTeams(){$('teams-grid').innerHTML=teams.map(t=>`<article class="team-card"><small>Group ${t[1]}</small><strong>${t[0]}</strong><p class="mb-2 text-secondary">核心球员：${t[3]}</p><div class="meter"><span style="width:${t[2]}%"></span></div><small>综合实力 ${t[2]}</small></article>`).join('')}
function renderStandings(){const groups=['A','B','C','D','E'];$('standings-content').innerHTML=groups.map(g=>`<article class="standing-card"><strong>Group ${g}</strong><div class="standing-row text-secondary"><span>Team</span><b>场</b><b>胜</b><b>平</b><b>负</b><b>分</b></div>${teams.filter(t=>t[1]===g).map((t,i)=>`<div class="standing-row"><span>${t[0]}</span><b>${i+1}</b><b>${i?0:1}</b><b>${i?1:0}</b><b>0</b><b>${i?1:3}</b></div>`).join('')}</article>`).join('')}
function renderPrediction(){let best='--',bestPct=0;$('prediction-board').innerHTML=demoMatches.map(m=>{const p=prediction(m);const top=Object.entries(p).sort((a,b)=>b[1]-a[1])[0];if(top[1]>bestPct){bestPct=top[1];best=`${m.home} ${label(top[0])} ${top[1]}%`}return`<article class="prediction-card"><strong>${m.home} vs ${m.away}</strong>${['HOME','DRAW','AWAY'].map(s=>`<div class="prob-row"><span>${label(s)}</span><div class="meter"><span style="width:${p[s]}%"></span></div><b>${p[s]}%</b></div>`).join('')}<small class="text-warning">推荐：${label(top[0])}</small></article>`}).join('');$('top-pick').innerText=best}
function placeBet(selection,matchId=selectedMatchId){const stake=Number.parseInt($('stake-input').value,10);if(!Number.isFinite(stake)||stake<=0)return alert('请输入有效投注积分。');if(currentPoints<stake)return alert('积分不足，请先充值。');const m=demoMatches.find(x=>x.id===matchId);const o=getCurrentOdds(matchId);const bet={id:`bet-${Date.now()}`,matchId:m.id,matchLabel:`${m.home} vs ${m.away}`,matchDate:m.date,selection,selectionLabel:label(selection),stake,odds:o[selection],potentialReturn:+(stake*o[selection]).toFixed(2),status:'pending',createdAt:new Date().toISOString()};const bets=readJson(STORAGE_KEYS.bets,[]);bets.unshift(bet);writeJson(STORAGE_KEYS.bets,bets);updatePoints(currentPoints-stake);renderAllDynamic();alert(`投注成功：${bet.matchLabel} · ${bet.selectionLabel} @ ${bet.odds}`)}
function renderMyBets(){const bets=readJson(STORAGE_KEYS.bets,[]);$('my-bets-list').innerHTML=bets.length?bets.map(b=>`<article class="bet-row"><div><strong>${b.matchLabel}</strong><div class="small text-secondary">${b.matchDate} · ${new Date(b.createdAt).toLocaleString()}</div></div><div>${b.selectionLabel}</div><div>${b.stake} PTS</div><div>@ ${Number(b.odds).toFixed(2)}</div><div class="text-warning">预计返还 ${b.potentialReturn}</div><span class="badge text-bg-secondary">${b.status}</span></article>`).join(''):'<div class="empty-state">暂无投注记录。选择比赛和赔率后即可保存到这里。</div>'}
function renderBettingPool(){const bets=readJson(STORAGE_KEYS.bets,[]);$('total-pool-points').innerText=`${bets.reduce((s,b)=>s+b.stake,0)} PTS`;$('betting-pool').innerHTML=demoMatches.map(m=>{const mb=bets.filter(b=>b.matchId===m.id),total=mb.reduce((s,b)=>s+b.stake,0);return`<article class="pool-card"><div class="d-flex justify-content-between"><strong>${m.home} vs ${m.away}</strong><span>${total} PTS</span></div>${['HOME','DRAW','AWAY'].map(s=>{const amount=mb.filter(b=>b.selection===s).reduce((x,b)=>x+b.stake,0),pct=total?Math.round(amount/total*100):0;return`<div class="pool-option"><span>${label(s)}</span><div class="progress"><div class="progress-bar bg-warning" style="width:${pct}%"></div></div><small>${amount} PTS · ${pct}%</small></div>`}).join('')}</article>`}).join('')}
function renderLiveOdds(){$('live-odds-board').innerHTML=demoMatches.map(m=>`<article class="pool-card"><div class="d-flex justify-content-between mb-2"><strong>${m.home} vs ${m.away}</strong><small>${m.date} ${m.time}</small></div><div class="quick-odds">${oddsButtons(m.id,'quick-odd')}</div></article>`).join('')}
function renderSearchResults(q){const shell=$('search-results'),list=$('search-results-list'),n=q.trim().toLowerCase();if(!n){shell.classList.add('d-none');return}const found=demoMatches.filter(m=>[m.home,m.away,m.date,m.group,m.venue].some(v=>v.toLowerCase().includes(n)));shell.classList.remove('d-none');$('search-count').innerText=`${found.length} 条`;list.innerHTML=found.length?found.map(m=>`<button class="result-card" data-match-id="${m.id}"><strong>${m.home} vs ${m.away}</strong><span>${m.date} ${m.time} · ${m.group} · ${m.venue}</span></button>`).join(''):'<div class="empty-state">没有找到相关球队或比赛。</div>'}
function showRoute(route){document.querySelectorAll('.route-page').forEach(p=>p.classList.toggle('d-none',p.dataset.page!==route));document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===route))}
function redeemCard(){const code=$('card-code').value.trim();if(!/^DEMO-2026$/i.test(code))return alert('演示环境仅接受 DEMO-2026。');updatePoints(currentPoints+100);$('card-code').value='';alert('演示卡密兑换成功：+100 PTS。')}
function saveProfile(){const p={name:$('auth-name').value.trim()||'Demo User',email:$('auth-email').value.trim(),savedAt:new Date().toISOString()};writeJson(STORAGE_KEYS.profile,p);$('auth-button').innerText=p.name}
function renderAllDynamic(){renderSelectedMatch();renderOdds();renderMatches();renderTeams();renderStandings();renderPrediction();renderMyBets();renderBettingPool();renderLiveOdds()}
function boot(){updatePoints();const p=readJson(STORAGE_KEYS.profile,null);if(p?.name)$('auth-button').innerText=p.name;renderMatchSelect();renderAllDynamic();$('match-select').addEventListener('change',e=>{selectedMatchId=e.target.value;renderSelectedMatch();renderOdds()});document.body.addEventListener('click',e=>{const route=e.target.closest('[data-route]');if(route){e.preventDefault();showRoute(route.dataset.route)}const pick=e.target.closest('[data-match-id]');if(pick){selectedMatchId=pick.dataset.matchId;if($('match-select'))$('match-select').value=selectedMatchId;renderSelectedMatch();renderOdds();if(pick.classList.contains('pick-match')||pick.classList.contains('result-card'))showRoute('home')}const odd=e.target.closest('[data-selection]');if(odd)placeBet(odd.dataset.selection,odd.dataset.matchId||selectedMatchId)});$('site-search').addEventListener('input',e=>renderSearchResults(e.target.value));$('redeem-card').addEventListener('click',redeemCard);$('refresh-pool').addEventListener('click',renderBettingPool);$('clear-bets').addEventListener('click',()=>{if(confirm('确定清空本地投注记录？')){writeJson(STORAGE_KEYS.bets,[]);renderAllDynamic()}});$('save-profile').addEventListener('click',saveProfile);setInterval(()=>{renderOdds();renderLiveOdds();renderPrediction()},20000)}
document.addEventListener('DOMContentLoaded',boot);
